name: Main
on: push
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  deploy_API:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3     
        
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::211125726271:role/GitHub
          aws-region: eu-north-1
      - name: Deploy
        #STAGE: prod
        run: |
          sudo apt-get update
          sudo apt-get -y install apt-transport-https
          wget -qO- https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /usr/share/keyrings/dart.gpg
          echo 'deb [signed-by=/usr/share/keyrings/dart.gpg arch=amd64] https://storage.googleapis.com/download.dartlang.org/linux/debian stable main' | sudo tee /etc/apt/sources.list.d/dart_stable.list
          sudo apt-get update
          sudo apt-get -y install dart zip
          mkdir build
          npm install --save-dev aws-sdk@2.1259.0
          npm install serverless
          npx serverless plugin install --name serverless-iam-roles-per-function
          dart pub get
          dart compile exe lib/main.dart -o build/bootstrap
          cd build
          zip bootstrap.zip ./*
          cd ..
          npx serverless deploy